# ======================================
# 模型指定
# ======================================
model: TTARArec

# ======================================
# 预训练模型配置
# ======================================
pretrained_model_type: bert4rec  # 支持: duorec, sasrec
pretrained_model_path: "./log/BERT4Rec/Amazon_Beauty/bs128-lmdNone-semNone-None-Sep-24-2025_13-53-05-lr0.001-l20.0-tauNone-None-DPh0.1-DPa0.5/model.pth"

# DuoRec特定参数
lmd: 0.1
lmd_sem: 0.2
contrast: 'us_x'
tau: 1.0
sim: 'dot'

# Transformer模型参数
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0
attn_dropout_prob: 0
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
training_neg_sample_num: 0
# ======================================
# 目录设置
# ======================================
log_root: "./log/"
data_path: "./recbole/dataset"

# ======================================
# 数据集配置
# ======================================
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, rating, timestamp]

NEG_PREFIX: neg_
LABEL_FIELD: label
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

min_user_inter_num: 5
min_item_inter_num: 5

# ======================================
# 训练设置
# ======================================
epochs: 200
train_batch_size: 256
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
weight_decay: 0

# ======================================
# 评估设置
# ======================================
eval_batch_size: 256
eval_setting: TO_LS,full
metrics: ["Recall", "NDCG","MRR"]
valid_metric: NDCG@10
topk: [5, 10, 20, 50]

# ======================================
# TTARArec检索增强参数
# ======================================
nprobe: 1                       # Faiss检索探针数
top_k: 10                         # 检索top-k个相似序列
low_popular: 100                 # 低热度阈值，序列长度小于此值才使用增强
len_lower_bound: -1              # 序列长度下界，-1表示不限制
len_upper_bound: -1              # 序列长度上界，-1表示不限制
len_bound_reverse: False          # 是否反转长度过滤条件

# ======================================
# 检索器编码器参数
# ======================================
retriever_layers: 1              # 检索器MLP层数
retriever_dropout: 0           # 检索器Dropout率


# ======================================
# 交叉注意力融合机制参数（独立于预训练模型）
# ======================================
fusion_n_heads: 1               # 交叉注意力头数
fusion_inner_size: 256          # 交叉注意力FFN内部维度
fusion_dropout_prob: 0        # 交叉注意力dropout概率
fusion_layer_norm_eps: 1e-12    # 交叉注意力LayerNorm epsilon

# ======================================
# 损失函数和融合权重参数
# ======================================
kl_loss_weight:  0.2            # KL散度损失权重

# ======================================

#检索评分参数
retrieval_tau: 1